# Generated by Django 5.1 on 2024-08-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BFSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggmonitor',
            name='added_eggs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='amount_of_added_eggs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='avg_single_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='comments',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='egg_weight_1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='egg_weight_2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='egg_weight_3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='fertelity_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='fertile_eggs_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='fertile_eggs_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='fertile_eggs_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='incubation_temp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='incubation_tube',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='infertile_eggs_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='infertile_eggs_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='infertile_eggs_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='num_eggs_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='num_eggs_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='num_eggs_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='rsd_fertelity_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='rsd_single_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='target_density',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eggmonitor',
            name='total_eggs_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
