# Generated by Django 5.1 on 2024-08-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BFSapp', '0002_alter_eggmonitor_added_eggs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedmonitor',
            name='cage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breedmonitor',
            name='days_from_cage_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breedmonitor',
            name='first_emergence_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breedmonitor',
            name='harvest_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breedmonitor',
            name='starter_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
