# Generated by Django 5.1 on 2024-08-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BFSapp', '0003_alter_breedmonitor_cage_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedmonitor',
            name='days_from_cage_date',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
